language: python
python:
- 2.7
- 3.3
- 3.4
install:
- pip install coveralls
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
before_script:
- make env
- make depends-ci
script:
- make ci
after_success:
- coveralls
- ocular
notifications:
  email:
    on_success: never
    on_failure: change